title: LunaCrew's Base32
description: Base32 encoding and decoding library
theme: just-the-docs
color_scheme: dark
url: https://lunacrew.github.io/base32

heading_anchors: true
nav_enabled: true

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: "k"

# logo: "/assets/logo.png"
# favicon: "/assets/favicon.ico"
